apiVersion: apps/v1
kind: Deployment
metadata:
  name: ScreeningManage
  labels:
    app: ScreeningManage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ScreeningManage
  template:
    metadata:
      labels:
        app: ScreeningManage
    spec:
      containers:
        - name: ScreeningManage
          image: username/ScreeningManage:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5